### ISSUE TITLE
IE9 input.type problem

### ISSUE THREAD

**Issue by cquest** [komoot/leaflet.photon#10]
IE9 does not like this.input.type = 'search';

https://github.com/komoot/leaflet.photon/blob/master/leaflet.photon.js#L104

When commenting this line IE9 does not complain anymore.

**Comment by yohanboniface** [comment]
What's the error?

**Comment by cquest** [comment]
Invalid argument... it looks like IE9 does not allow to change the input field type or does not accept "search" as a type.
